export const en = {
    login: "login",
    register: "register",
    sign_in: 'sign in',
    Sign_out: 'Sign out',
    app_title: 'jomle',
    app_title_: 'app title',
    app_logo: 'jomle',
    brand_name: 'jomle',
    dashboard: 'dashboard',
    user_manage: 'user manage',
    user: 'user',
    user_create: 'user create',
    forgot_password: 'forgot password?',
    msg: {
        ui: {
            msg1: 'action succeeded',
            msg2: 'error occurred',
            msg3: 'registered successfully, we redirect you to login page.',
            msg4: 'password changed successfully, we redirect you to login page.',
            no_network_connection: 'error occurred, please check your network connection and try again',
            new_vesion_available_update: 'new vesion of app is available, you can update it.',
            item_will_be_removed_continue: 'item will be removed continue?',
            img_not_uploaded_max_size_n: 'the file could not be uploaded, use only "image" with size less than "{0}"',
            one_img_upload_allowed_remove_existing_one: "one img upload allowed, remove existing one",
            login_again: 'login again',
            sync_error: 'error occured while syncing',
            change_password_successful: 'password successfully changed',
        },
        back: {
            signup_token_not_exists: 'Your registration has expired, please start the registration process from the beginning.',
            invalid_signup_token: 'Your registration has expired, please start the registration process from the beginning.',
            token_invalid: 'login again',
            token_expired: 'token expired',
            delete_failed: 'deleting failed',
            get_failed: 'getting failed',
            commit_failed: 'commiting to database failed',
            no_auth: 'you are not logged in',
            invalid_username: 'username or password is not valid',
            invalid_enum: 'enum is not correct  type',
            not_found: 'entity not found',
            access_denied: 'user has not access to this action',
            missing_requiered_field: 'missing requiered field',
            already_exists: 'entity already exists',
            invalid_password: 'password is invalid',
        }
    },
    validation: {
        minLength: 'min length {value} character',
        mobileFormat: 'mobile format is not valid',
        smsCodeFormat: 'code is not valid.',
        confirmPassword: 'confirm password not match password.',
        emailFormat: 'email format is not valid',
        phoneFormat: 'phone format is not valid',
    },
    username: 'username',
    password: 'password',
    name: 'name',
    lastname: 'last name',
    phone: 'phone',
    address: 'address',
    mobile: 'mobile',
    email: 'email',
    confirm_password: 'confirm password',
    old_password: 'old password',
    new_password: 'new password',
    confirm_new_password: 'confirm new password',
    invalid_value: 'invalid value',
    required_field: 'required field',
    Show_password: 'Show password',

    submit: 'submit',
    in: 'in',
    second: 'second',
    search: 'search',
    home: 'home',
    more: 'more',
    loading_with_dots: 'loading...',
    retry: 'retry',
    title: 'title',
    return: 'return',
    reset_password: 'reset password',
    log_out: 'log out',
    sync: 'sync',
    settings: 'settings',
    info: 'info',
    Length: 'Length',
    pages: 'pages',
    description: 'description',
    language: 'language',
    follow: 'follow',
    unfollow: 'unfollow',
    see_more: 'see more',
    see_less: 'see less',
    format: 'format',
    all: 'all',
    of: 'of',
    from: 'from',
    to: 'to',
    agent: 'agent',
    previous: 'previous',
    next: 'next',
    no_item_found: 'no item found',

    load_more: 'load more',
    remove: 'remove',
    minute: 'minute',
    hour: 'hour',
    close: 'close',
    app_info: 'app info',
    version: 'version',
    version_mode: 'version mode',
    trial_mode: 'trial mode',
    trial: 'trial',
    dont_want_now: "i don't want now",
    update: 'update',
    shopping_cart: 'shopping cart',

    buy: 'buy',
    price: 'price',
    total_price: 'total price',
    recalculate: 'recalculate',
    view_detail: 'view detail',
    cancel: 'cancel',
    ok: 'ok',
    create: 'create',

    rename: 'rename',
    download: 'download',
    downloading: 'downloading',
    add: 'add',
    selected: 'selected',
    select_all: 'select all',
    deselect_all: 'deselect all',
    profile: "profile",
    profile_image: "profile image",
    preview: "preview",
    drag_and_drop: "drag and drop",
    choose_image: 'choose image',
    goto: 'go to',
    go: 'go',
    page_not_found: 'page not found',
    detail: 'detail',
    count: 'count',
    unit_price: 'unit price',
    type: 'type',
    text_size: 'text size',
    theme: 'theme',
    font: 'font',


    change_password: 'change password',
    storage: 'storage',
    state: 'state',
    confirm: 'confirm',
    clear: 'clear',
    unknown: 'unknown',
    operating_system: 'operating system',
    browser: 'browser',
    device: 'device',
    this_device: 'this device',
    zoom: 'zoom',
    reload_app: 'reload application',
}