export const fa = {
    login: "ورود",
    register: "ثبت نام",
    sign_in: 'ورود',
    Sign_out: 'خروج از سیستم',
    app_title: 'جمله',
    app_title_: 'عنوان برنامه',
    app_logo: 'جمله',
    brand_name: 'جمله',
    dashboard: 'داشبورد',
    user_manage: 'مدیریت کاربر',
    user: 'کاربر',
    user_create: 'ایجاد کاربر',
    forgot_password: 'رمز عبورتان را فراموش کردید؟',
    msg: {
        ui: {
            msg1: 'عملیات با موفقیت انجام شد.',
            msg2: 'خطا رخ داد.',
            msg3: 'ثبت نام با موفقیت انجام شد، به صفحه ورود منتقل می شوید.',
            msg4: 'رمز عبور با موفقیت تغییر کرد، به صفحه ورود منتقل می شوید.',
            no_network_connection: 'خطا رخ داد، لطفا دسترسی اینترنت خود را بررسی کرده و مجددا تلاش کنید.',
            new_vesion_available_update: 'نسخه جدیدی از برنامه موجود است، می توانید آن را بروز کنید.',
            item_will_be_removed_continue: 'رکورد مورد نظر حذف خواهد شد، تایید می کنید؟',
            img_not_uploaded_max_size_n: 'فایل قابل آپلود نیست، فقط "تصویر" و با اندازه ای کمتر از "{0}" انتخاب کنید',
            one_img_upload_allowed_remove_existing_one: "تنها می توانید یک تصویر بارگذاری کنید، لطفا عکس فعلی را حذف کنید.",
            login_again: 'مجددا وارد شوید',
            sync_error: 'هنگام همگام سازی خطایی روی داد',
            change_password_successful: 'رمز عبور با موفقیت بروز شد',
        },
        back: {
            signup_token_not_exists: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',
            invalid_signup_token: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',
            token_invalid: 'مجددا وارد شوید',
            token_expired: 'مجددا وارد شوید',
            delete_failed: 'خطا در حذف اطلاعات از سرویس دهنده رخ داد.',
            get_failed: 'خطا در دریافت اطلاعات از سرویس دهنده رخ داد.',
            commit_failed: 'سرویس دهنده با خطا مواجه شد.',
            no_auth: 'شما وارد نشده اید',
            invalid_username: 'نام کاربری یا رمز عبور اشتباه است.',
            invalid_enum: 'enum is not correct  type',
            not_found: 'مورد، یافت نشد.',
            access_denied: 'دسترسی به این مورد امکانپذیر نمی باشد',
            missing_requiered_field: 'موارد ضروری را پر کنید',
            already_exists: 'از قبل وجود دارد.',
            invalid_password: 'رمز عبور اشتباه است',
        }
    },
    validation: {
        minLength: 'حداقل {value} کاراکتر',
        mobileFormat: 'فرمت موبایل صحیح نیست',
        smsCodeFormat: 'فرمت کد صحیح نیست.',
        confirmPassword: 'رمز عبور با تایید آن همخوانی ندارد.',
        emailFormat: 'فرمت ایمیل صحیح نیست',
        phoneFormat: 'فرمت تلفن صحیح نیست',
    },
    username: 'نام کاربری',
    password: 'رمز عبور',
    name: 'نام',
    lastname: 'نام خانوادگی',
    phone: 'تلفن',
    address: 'آدرس',
    mobile: 'تلفن همراه',
    email: 'ایمیل',
    confirm_password: 'تایید رمز عبور',
    old_password: 'رمز عبور قبلی',
    new_password: 'رمز عبور جدید',
    confirm_new_password: 'تایید رمز عبور جدید',
    invalid_value: 'مقدار نامعتبر است',
    required_field: 'فیلد ضروری است',
    Show_password: 'نمایش رمزعبور',
    submit: 'ثبت',
    in: 'در',
    second: 'ثانیه',
    search: 'جستجو',
    home: 'خانه',
    more: 'بیشتر',
    loading_with_dots: 'درحال بارگذاری...',
    retry: 'تلاش مجدد',
    title: 'عنوان',
    return: 'بازگشت',
    reset_password: 'تغییر رمز عبور',
    log_out: 'خروج',
    sync: 'همگام سازی',
    settings: 'تنظیمات',
    info: 'اطلاعات',
    Length: 'اندازه',
    pages: 'صفحه',
    description: 'توضیحات',
    language: 'زبان',
    follow: 'دنبال کردن',
    unfollow: 'دنبال نکردن',
    see_more: 'بیشتر ببینید',
    see_less: 'کمتر ببینید',
    format: 'قالب',
    all: 'همه',
    of: 'از',
    from: 'از',
    to: 'تا',
    agent: 'نماینده',
    previous: 'قبلی',
    next: 'بعدی',
    no_item_found: 'موردی یافت نشد',
    load_more: 'بارگذاری بیشتر',
    remove: 'حذف',
    minute: 'دقیقه',
    hour: 'ساعت',
    close: 'بستن',
    app_info: 'اطلاعات برنامه',
    version: 'نسخه',
    version_mode: 'نوع نسخه',
    trial_mode: 'نسخه آزمایشی',
    trial: 'آزمایشی',
    dont_want_now: "فعلا نمی خواهم",
    update: 'بروزرسانی',
    shopping_cart: 'سبد خرید',
    buy: 'خرید',
    price: 'قیمت',
    total_price: 'قیمت کل',
    recalculate: 'محاسبه مجدد',
    view_detail: 'نمایش جزئیات',
    cancel: 'انصراف',
    ok: 'تایید',
    create: 'ایجاد',
    rename: 'تغییر نام',
    download: 'دانلود',
    downloading: 'درحال دانلود',
    add: 'افزودن',
    selected: 'انتخاب شده',
    select_all: 'انتخاب همه',
    deselect_all: 'لغو انتخاب همه',
    profile: "پروفایل",
    profile_image: "تصویر پروفایل",
    preview: "پیش نمایش",
    drag_and_drop: "بکشید و رها کنید",
    choose_image: 'انتخاب تصویر',
    goto: 'برو به',
    go: 'برو',
    page_not_found: 'صفحه یافت نشد',
    detail: 'جزئیات',
    count: 'تعداد',
    unit_price: 'قیمت واحد',
    type: 'نوع',
    text_size: 'اندازه قلم',
    theme: 'تم',
    font: 'فونت',
    change_password: 'تغییر رمز عبور',
    storage: 'مخزن',
    state: 'وضعیت',
    confirm: 'تایید',
    clear: 'پاک کن',
    unknown: 'نامشخص',
    operating_system: 'سیستم عامل',
    browser: 'مرورگر',
    device: 'دستگاه',
    this_device: 'این دستگاه',
    zoom: 'بزرگنمایی',
    reload_app: 'بارگیری مجدد برنامه',
}